(define-module (links)
                 #:use-module (haunt skribe utils)
                 #:export (%carpentries))
                 (define (%carpentries)
                          (anchor "the Carpentries" "https://carpentries.org"))
